drop table if EXISTS Users;
DROP TABLE IF EXISTS Quizzers;
DROP TABLE IF EXISTS Questions;
DROP TABLE IF EXISTS Options;
DROP TABLE IF EXISTS Results;


CREATE TABLE Users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT UNIQUE NOT NULL,
password TEXT NOT NULL
);

CREATE TABLE Quizzers(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
description TEXT
);

CREATE TABLE Questions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
quiz_id INTEGER NOT NULL,
text TEXT NOT NULL,
FOREIGN KEY (quiz_id) REFERENCES Quizzers(id)
);

CREATE TABLE Results(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER NOT NULL,
quiz_id INTEGER NOT NULL,
score INTEGER NOT NULL,
FOREIGN KEY (user_id) REFERENCES Users(id),
FOREIGN KEY (quiz_id) REFERENCES Quizzers(id)
);




